### PR TITLE
Disable `disallowKeywordsInComments` rule

### PR DESCRIPTION
**Pull request by promag**
This change allows comments like `// TODO` and `//FIXME`.

### CODE REVIEW

**Comment by JoaoHenriquePereira** [comment]
:-1: for general rule. Would rather use `disallowKeywordsInComments: false` for specific projects. /cc @ruimarinho @nunofgs @fixe

**Comment by ruiquelhas** [comment]
@promag do you still think this makes sense?

**Comment by ruimarinho** [comment]
Why is TODO and FIXME considered a keyword? Aren't those related to javascript keywords?

**Comment by promag** [comment]
@JoaoHenriquePereira it's common to have these comments when submitting WIP code. In those cases the commit can be created with no verifications I guess. Therefore I agree with your suggestion.

**Pull request closed without merging**
